-- V1 baseline: the schema produced by the original Hibernate ddl-auto: update setup,
-- captured so Flyway owns it from here on.
--
-- PostgreSQL-specific types are used here (BYTEA, TIMESTAMP WITH TIME ZONE).
-- The H2 twin lives in db/migration/h2/V1__baseline.sql - keep the two in sync.

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR(100)  NOT NULL,
    email         VARCHAR(255)  NOT NULL,
    password_hash VARCHAR(100)  NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE resumes (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id      BIGINT        NOT NULL,
    name         VARCHAR(200)  NOT NULL,
    file_name    VARCHAR(255)  NOT NULL,
    content_type VARCHAR(150),
    file_type    VARCHAR(20)   NOT NULL,
    version_tag  VARCHAR(200),
    file_size    BIGINT        NOT NULL,
    file_data    BYTEA         NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_resumes PRIMARY KEY (id),
    CONSTRAINT fk_resumes_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE jobs (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id           BIGINT         NOT NULL,
    company_name      VARCHAR(150)   NOT NULL,
    job_title         VARCHAR(150)   NOT NULL,
    job_url           VARCHAR(1000),
    description       VARCHAR(20000),
    location          VARCHAR(200),
    salary_range      VARCHAR(100),
    status            VARCHAR(30)    NOT NULL,
    applied_date      DATE,
    target_apply_date DATE,
    outcome           VARCHAR(30),
    outcome_reason    VARCHAR(30),
    feedback          VARCHAR(5000),
    notes             VARCHAR(10000),
    resume_id         BIGINT,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_jobs PRIMARY KEY (id),
    CONSTRAINT fk_jobs_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_jobs_resume FOREIGN KEY (resume_id) REFERENCES resumes (id)
);

CREATE INDEX idx_jobs_user_updated_at ON jobs (user_id, updated_at);
CREATE INDEX idx_resumes_user_created_at ON resumes (user_id, created_at);
