-- V2: richer job details plus an audit trail of pipeline transitions.

ALTER TABLE jobs ADD COLUMN work_mode      VARCHAR(20);
ALTER TABLE jobs ADD COLUMN deadline       DATE;
ALTER TABLE jobs ADD COLUMN job_source     VARCHAR(100);
ALTER TABLE jobs ADD COLUMN salary_min     BIGINT;
ALTER TABLE jobs ADD COLUMN salary_max     BIGINT;
ALTER TABLE jobs ADD COLUMN salary_currency VARCHAR(3);

-- Free-form labels such as "remote-friendly", "referral", "dream job".
CREATE TABLE job_tags (
    job_id BIGINT      NOT NULL,
    tag    VARCHAR(50) NOT NULL,
    CONSTRAINT pk_job_tags PRIMARY KEY (job_id, tag),
    CONSTRAINT fk_job_tags_job FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE CASCADE
);

-- One row per status transition, so "recent activity" becomes a real event log
-- instead of an inference from updated_at.
CREATE TABLE job_status_history (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    job_id      BIGINT      NOT NULL,
    from_status VARCHAR(30),
    to_status   VARCHAR(30) NOT NULL,
    changed_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    note        VARCHAR(500),
    CONSTRAINT pk_job_status_history PRIMARY KEY (id),
    CONSTRAINT fk_job_status_history_job FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE CASCADE
);

CREATE INDEX idx_job_status_history_job ON job_status_history (job_id, changed_at);
CREATE INDEX idx_job_tags_tag ON job_tags (tag);
