-- V5 (H2 twin). Identical to the PostgreSQL migration: no vendor-specific types here.

CREATE TABLE cover_letters (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id      BIGINT      NOT NULL,
    job_id       BIGINT,
    name         VARCHAR(200) NOT NULL,
    body         VARCHAR(20000),
    file_name    VARCHAR(255),
    content_type VARCHAR(150),
    file_type    VARCHAR(20),
    file_size    BIGINT,
    storage_key  VARCHAR(255),
    version_tag  VARCHAR(200),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_cover_letters PRIMARY KEY (id),
    CONSTRAINT fk_cover_letters_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_cover_letters_job FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE SET NULL
);

CREATE INDEX idx_cover_letters_user ON cover_letters (user_id, created_at);
